### PR TITLE
add dynamic icon and tooltip

### PR DESCRIPTION
**Pull request by simonbuehler**
hi, 

my approach for #1 , adds a subtle icon and success feedback

### CODE REVIEW

**Comment by saadj55** [comment]
Thanks for the PR,

I would prefer the copy icon visible at all times, just for a better user experience and indication that this cell can be copied. 

Also, if we could stick to `<x-heroicon-o-clipboard />` icon, that would be great. 

Other than above, great PR. thanks for your help.

Looking forward for the changes.

**Comment by simonbuehler** [comment]
tastes are different 😉 
for a project the client doesn't want to have the table full with icons, maybe i make the fading and the actual icon configurable

**Comment by simonbuehler** [comment]
default behaviour is same, can be configured using `->animated()` or `->icon("heroicon-o-duplicate")` as one likes

**Comment by simonbuehler** [comment]
should be good to go

**Comment by saadj55** [comment]
thanks for the updates, I will review now

**Comment by MACscr** [comment]
Please merge =)

**Comment by simonbuehler** [comment]
@saadj55  did you review,?

**Pull request merged**
